version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:14
    working_directory: ~/cake_app
    resource_class: small

jobs:
  build:
    executor: node
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: ~/cake_app
          paths: ['.']
  test:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests
          command: npm run test
  save:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - store_artifacts:
          path: ./build
          destination: build/

workflows:
  build_and_test:
    jobs:
    - build
    - test:
        requires:
          - build
    - save:
        requires:
          - test