# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - node/build:
        working_directory: ~/cake-calc
        docker:
          - image: circleci/node:8
        steps:
          - checkout
          - restore_cache:
            key: npm-cache-v1-{{ checksum "package-lock.json" }}
          - run:
            name: Install Dependencies
            command: npm ci
          - save_cache:
            key: npm-cache-v1-{{ checksum "package-lock.json" }}
            paths:
              - /home/circleci/.npm
          - run:
            name: Run Tests
            command: npm test
