# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:14
    working_directory: ~/cake_app


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
jobs:
  build:
    executor: node
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Build
          command: npm run build
  test:
    executor: node
    steps:
      attach_workspace:
        at: .
      - run:
          name: Run Tests
          command: npm run test

workflows:
  build_and_test:
    jobs:
    - build
    - test:
        requires:
          - build